- hosts: all
  tasks:
  - file:
      state: directory
      path: /dvd

  - mount:
      path: "/dvd"
      src: "/dev/cdrom"
      state: mounted
      fstype: "iso9660"

  - yum_repository:
      baseurl: "/dvd/AppStream"
      name: "mydvd1"
      description: "AppStream"
      gpgcheck: no

  - yum_repository:
      baseurl: "/dvd/BaseOS"
      name: "mydvd2"
      description: "BaseOS"
      gpgcheck: no

  - yum_repository:
      baseurl: "http://docker-release-purple-prod.s3-website-us-east-1.amazonaws.com/linux/centos/7/x86_64/stable/"
      name: "docker"
      description: "docker"
      gpgcheck: no

  - package:
      name: "docker-ce-18.09.1-3.el7.x86_64"
      state: present

  - service:
      name: "docker"
      state: started
      enabled: yes

  - package:
      name: "python36"
      state: present

  - pip:
      name: docker
      executable: pip3 

  - docker_image:
      name: "httpd"
      source: pull

  - file:
      state: directory
      path: /webserver
 
  - copy:
      src: "/root/ansible/copyfiles/index.html"
      dest: "/webserver"

  - docker_container:
      name: "Webserver"
      image: "httpd"
      state: started
      exposed_ports: "80"
      ports: "8080:80"
      volumes: "/webserver:/usr/local/apache2/htdocs/"

